#!/bin/sh

# author: abdul2926

# --Autostart--
pgrep -x sxhkd > /dev/null || sxhkd &
vyprvpn c &
feh --bg-fill ~/Images/Wallpapers/wp8635721-genshin-impact-fischl-wallpapers.jpg & 
picom &

# --Workspaces--
bspc monitor -d I II III IV V VI VII VIII IX X

# --Appearance--
bspc config border_width 0
bspc config window_gap 15
bspc config split_ratio 0.5

# --Border--
bspc config focused_border_color "#62468c"
bspc config normal_border_color "#2e3136"
bspc config border_width 2

# --Rules--
bspc rule -a Thunar state=floating
bspc rule -a screengrab state=floating
