#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill ~/Images/wallpaper.jpg &
xinput set-prop 10 303 0 1 &
xrandr --output DP-2 --mode 1920x1080 --rate 144.00 &

# Workspaces
bspc monitor -d I II III IV V

# Appearance
bspc config border_width	1
bspc config window_gap		15
bspc config split_ratio		0.5
bspc config normal_border_color \#564848
bspc config focused_border_color \#E05151
